name: Build and Upload Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Server Compilation
      - name: Install server dependencies
        run: npm install
        working-directory: server

      - name: Build Express Server
        run: npm run build
        working-directory: server

      - name: Upload compiled server files
        uses: actions/upload-artifact@v4
        with:
          name: compiled-server-dist
          path: server/dist/
          retention-days: 5

      # Webapp Compilation
      - name: Install webapp dependencies
        run: npm install
        working-directory: webapp

      - name: Build Vite React App
        run: npm run build
        working-directory: webapp

      - name: Upload compiled webapp files
        uses: actions/upload-artifact@v4
        with:
          name: compiled-webapp-dist
          path: webapp/dist/
          retention-days: 5
